#include "Includes/Com.Google.Android.Gms.Common.Api/GoogleApiClient.h"
#include "Includes/Com.Google.Android.Gms.Common.Api/PendingResult`1.h"
#include "Includes/Com.Google.Android.Gms.Common.Api/Result.h"
#include "Includes/Com.Google.Android.Gms.Common.Api/ResultCallback`1.h"
#include "Includes/Com.Google.Android.Gms.Common.Api/ResultCallbackProxy`1.h"
#include "Includes/Com.Google.Android.Gms.Common.Api/Status.h"
